### ISSUE TITLE
[BUG REPORT] petit  bug parfois gênant

### ISSUE THREAD

**Issue by Woomymy** [LeRoiDesKiwis/KillThePlayer#1]
en appuyant sur les flèches pour bouger le jeu me force a aller a gauche de manière aléatoire

**Comment by LeRoiDesKiwis** [comment]
Je n'arrive pas à reproduire le bug, je close. Si c'est arrivé à quelqu'un d'autre, qu'il mette un message, je réouvrirais l'issue.
