### ISSUE TITLE
[FEATURE REQUEST] Système de logs en fichier

### ISSUE THREAD

**Issue by paulcomte** [LeRoiDesKiwis/KillThePlayer#2]
Description **complète** du la fonctionnalité :
Système de log
Lors de l'ouverture du jeu, un fichier à l'emplacement du jeu est crée, écrit "HH:MM-DD:MM:YEAR"
tel que "16:08-31/10/2019"
Ce fichier comportera toute les actions du joueur, sous cette forme
"16:09:10:23 > Player moved to 25:01" (à 16:09 et 10s et 23 milliseconde, le joueur a bougé sur la case x=25, et z=01)
Mais aussi pour le score
"16:09:10:23 > Player got 1 point (action_moving_left) total point = 10" (à 16:09 et 10s et 23 miliseconde, le joueur a obtenu 1 point, car il a bougé vers la gauche, son score total est de 10
De même pour les items
"16:09:11:12 > Player took item_kill at 21:04" (à 16:09 et 11s et 12 milliseconde, le joueur a pris l'item de kill d'ennemies sur la case x=21, et z=04)
Grâce à ce système de log, il sera plus simple de "debug"
Cordialement
Pour plus de précisions
 |
\/

**Comment by LeRoiDesKiwis** [comment]
Ok je l'ajoute sur le trello. Merci ^^.

**Comment by LeRoiDesKiwis** [comment]
Fait ! https://github.com/LeRoiDesKiwis/KillThePlayer/commit/c6d14a8308eb438400639085d98e4918e2cf4096
